#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_gogs_Darwin="https://github.com/gogits/gogs/releases/download/v${GOGS_VERSION}/darwin_amd64.zip"
  local url_gogs_Linux="https://github.com/gogits/gogs/releases/download/v${GOGS_VERSION}/linux_amd64.zip"

  local url_gogs="url_gogs_$(uname -s)"
  local fnm_gogs="$(basename "${!url_gogs}")-${GOGS_VERSION}"
  cache curl "$fnm_gogs" "${!url_gogs}"

  mkdir -p "$shome/vendor/gogs-${GOGS_VERSION}"
  pushd "$shome/vendor/gogs-${GOGS_VERSION}"
  unzip -o "${BASEBOX_CACHE}/curl/$fnm_gogs"
  popd

  pushd "$shome/bin"
  ln -nfs ../vendor/gogs-${GOGS_VERSION}/gogs/gogs .
  popd

}

bootstrap
