#!/usr/bin/env bash

function _gogs_profile {
  local shome="${_gogs_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"

  GOGS_VERSION="0.10.18"

  PATH="$shome/vendor/gogs-${GOGS_VERSION}/gogs:$PATH"
}

_gogs_profile
