#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_gogs="$(gogs -v 2>/dev/null | awk '{print $3}' | cut -d. -f1-3 || true)"
  jq -n --arg gogs "$ver_gogs" '{gogs: $gogs}'
}

version "$@"
